// <auto-generated />
using System;
using Harbor.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Harbor.Infrastructure.Migrations
{
    [DbContext(typeof(HarborDbContext))]
    [Migration("20260717130809_Sprint14Segments")]
    partial class Sprint14Segments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Harbor.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PublishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Status");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.ArticleCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Slug")
                        .IsUnique();

                    b.ToTable("ArticleCollections");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.AssignmentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActorTeammateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FromTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FromTeammateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ToTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ToTeammateId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("AssignmentEvents");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.CannedReply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Shortcut")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Shortcut")
                        .IsUnique();

                    b.ToTable("CannedReplies");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSeenAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Email");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AssignedTeammateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ClosedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FirstResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FirstRespondedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FirstResponseDueAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InboxId")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastMessageAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolutionDueAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SnoozedUntil")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTeamId");

                    b.HasIndex("AssignedTeammateId");

                    b.HasIndex("ContactId");

                    b.HasIndex("InboxId");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("WorkspaceId", "State");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.ConversationTag", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("ConversationId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ConversationTags");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Inbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoAssign")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FirstResponseSlaMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastAssignedTeammateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "EmailAddress")
                        .IsUnique();

                    b.ToTable("Inboxes");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorContactId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthorTeammateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthorType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorContactId");

                    b.HasIndex("AuthorTeammateId");

                    b.HasIndex("EmailMessageId");

                    b.HasIndex("ConversationId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Segment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RulesJson")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.SlaBreachEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BreachedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DueAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SlaPolicyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Kind")
                        .IsUnique();

                    b.ToTable("SlaBreachEvents");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FirstResponseMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InboxId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResolutionMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InboxId");

                    b.HasIndex("WorkspaceId", "InboxId", "Priority");

                    b.ToTable("SlaPolicies");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.TeamMembership", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeammateId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamId", "TeammateId");

                    b.HasIndex("TeammateId");

                    b.ToTable("TeamMemberships");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Teammate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Availability")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapacityLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "Email")
                        .IsUnique();

                    b.ToTable("Teammates");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeliveredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NextAttemptAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("WorkspaceId", "Status", "NextAttemptAt");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("WebhookSubscriptions");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SubscriptionId", "EventType");

                    b.ToTable("WebhookSubscriptionEvent");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Article", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.ArticleCollection", "Collection")
                        .WithMany("Articles")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.ArticleCollection", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.AssignmentEvent", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.CannedReply", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Contact", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Team", "AssignedTeam")
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Harbor.Domain.Entities.Teammate", "AssignedTeammate")
                        .WithMany()
                        .HasForeignKey("AssignedTeammateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Harbor.Domain.Entities.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Harbor.Domain.Entities.Inbox", "Inbox")
                        .WithMany()
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTeam");

                    b.Navigation("AssignedTeammate");

                    b.Navigation("Contact");

                    b.Navigation("Inbox");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.ConversationTag", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Tags")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Harbor.Domain.Entities.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Inbox", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Inboxes")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Message", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Contact", "AuthorContact")
                        .WithMany()
                        .HasForeignKey("AuthorContactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Harbor.Domain.Entities.Teammate", "AuthorTeammate")
                        .WithMany()
                        .HasForeignKey("AuthorTeammateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Harbor.Domain.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorContact");

                    b.Navigation("AuthorTeammate");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Segment", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.SlaBreachEvent", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.SlaPolicy", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Inbox", "Inbox")
                        .WithMany()
                        .HasForeignKey("InboxId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inbox");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Team", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.TeamMembership", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Harbor.Domain.Entities.Teammate", "Teammate")
                        .WithMany("Memberships")
                        .HasForeignKey("TeammateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Teammate");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Teammate", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.WebhookSubscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookSubscription", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookSubscriptionEvent", b =>
                {
                    b.HasOne("Harbor.Domain.Entities.WebhookSubscription", "Subscription")
                        .WithMany("Events")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.ArticleCollection", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Teammate", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.WebhookSubscription", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Harbor.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Inboxes");
                });
#pragma warning restore 612, 618
        }
    }
}
